version: 2

jobs:
    build:
        
        working_directory: ~/src
        
        docker:
            - image: circleci/openjdk:8-jdk-stretch
            - image: circleci/postgres:9.6.3-alpine
              environment:
                PROSGRES_USER: root
                POSTGRES_DB: circle_test
        
        steps:
            
            - checkout
            
            - restore_cache:
                key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefile-reports
            
            - store_artifacts:
                path: target/booking-app-backend-0.0.1-SNAPSHOT.jar