version: 2

jobs:
    build:
        
        working_directory: ~/Backend/src
        
        docker:
            - image: circleci/openjdk:8-jdk-stretch
            - image: circleci/postgres:9.6.3-alpine
              environment:
                PROSGRES_USER: root
                POSTGRES_DB: circle_test
        
        steps:
            
            - checkout
            
            - restore_cache:
                key: Backend/src-{{ checksum "pom.xml" }}
            
            - run: maven dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: Backend/src-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefile-reports
            
            - store_artifacts:
                path: target/Backend/src-0.0.1-SNAPSHOT.jar